Feat add button
Nimiretta/js-ts-webdev-tasks pull request #1
Opened 2024-12-14 18:56 UTC by YBiheza

create "components" folder and add "button" component

2024-12-15 20:35 UTC, Nimiretta requested changes
1. Please reorganize structure according to atomic design example (src/atoms/button/buttonComponents.ts)
2. Using 'template string' approach it will be difficult to add event listener to this button. Please rewrite it via document.createElement approach with returning HTML element from this function
3. What is the class "button"? I can't find such class in Tailwind docs. If you want to create default css class for this btn, please create it simultaneosly with button. It could be a set of classes using Tailwind or separate css file in src/atoms/button imported to buttonComponents.ts
4. I'd suggest making the input parameters more obvious. I mean not just classparam string but separate parameters like textColor, bgColor etc. Amd inside function make from them classList.
5. It would be great to have possibility to pass callback function here as a parameter
for example smth like this:
export function Button(cbFunc) {
   const btn = document.createElement('button');
   btn.addEventListener('click', cbFunc);
   return btn;
}

2025-01-04 00:45 UTC, Nimiretta requested changes

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/types.ts
> +};
Please move file types.ts to src folder. Path should be src/types.ts

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/AppButton.ts
> +    label,
Please add also innerHTML optional parameter and set a condition in function if passed innerHTML then use for content innerHTML, otherwise use label. And label in such case will be also optional. Example can be seen in https://github.com/Nimiretta/js-ts-webdev-tasks/pull/5/commits/6a05eb2bf776cfe2c70acbe16b545e5871b1f550
It's needed because on some buttons there is text with arrow sign.

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/AppButton.ts
> +    backgroundColor = 'rgba(0, 0, 0, 1)',
please use tailwind classes here. For black background as default value it will be class 'bg-black'.
You have outdated branch without tailwind config, you need to sync your branch with hometask-shop-co for getting correct tailwind config

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/AppButton.ts
> +    textColor = 'rgba(255, 255, 255, 1)',
The same thing as above. For default white color it will be class 'text-white'

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/AppButton.ts
> +    borderRadius = '62px',
There is no need to pass border radius as parameter because it is the same for all buttons in the project. You can use hardcoded tailwind class 'rounded-full' as described in https://tailwindcss.com/docs/border-radius#pill-buttons

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/AppButton.ts
> +    padding,
There is no need to pass padding as parameter. You can set fixed top and bottom padding in the function with class 'py-' as described in https://tailwindcss.com/docs/padding. For value you can investigate figma design and set smth average. e.g. 'py-3.5'. 
Another option is using height instead of padding as parameter with most used value as default. For example 'h-12'. 
In all cases content should be centered.
And for width set class 'w-full' because btn will be restricted by parent container.

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/AppButton.ts
> +    fontSize,
Default value can be tailwind class 'text-base' as the most used value.

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/AppButton.ts
> +    fontWeight,
There is no need to pass font weight as parameter because for all buttons it is the same and can be hardcoded as tailwind class 'font-medium'

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/AppButton.ts
> +    fontFamily = 'Rubik',
There is no need to pass font as parameter because for all buttons it is the same and can be hardcoded as tailwind class 'font-rubik'

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/AppButton.ts
> +    button.style.fontFamily = fontFamily;
Please don't use inline styles, add tailwind classes. You can use button.classList.add() method for adding hardcoded and passed as parameters classes

2025-01-04 00:45 UTC, Nimiretta commented on src/atoms/button/AppButton.ts
> +    button.style.fontFamily = fontFamily;
Also I'd suggest adding 'cursor-pointer' class for button

2025-01-04 00:50 UTC, Nimiretta commented
Also please add index.ts file to atoms directory with export AppButton function. Example can be seen in other PRs

2025-01-05 21:46 UTC, Nimiretta commented on src/types.ts
> +    //padding: string;
Please remove commented line

2025-01-05 21:47 UTC, Nimiretta approved these changes
LGTM, great refactor!
P.S. Don't forget to remove commented code

2025-01-06 12:52 UTC, eu-peregudova requested changes

2025-01-06 12:52 UTC, eu-peregudova commented on src/atoms/button/AppButton.ts
> +    button.type = 'button';
Would be beneficial to have an option to make submit type buttons

2025-01-06 12:52 UTC, eu-peregudova commented on src/atoms/button/AppButton.ts
> +    button.type = 'button';
But in this case also "onSubmit" event might be useful

2025-01-06 19:35 UTC, eu-peregudova requested changes

2025-01-06 19:35 UTC, eu-peregudova commented on src/types.ts
> +    onClick: () => void;
This has to be optional, because for example type submit button doesn't need it

2025-01-07 19:53 UTC, eu-peregudova approved these changes
LGTM 👌

2025-01-07 19:56 UTC, merged