feat: add filterOption atom
Nimiretta/js-ts-webdev-tasks pull request #8
Opened 2024-12-29 15:19 UTC by Nimiretta

https://trello.com/c/my1Wfva1

2025-01-02 18:26 UTC, eu-peregudova requested changes

2025-01-02 18:26 UTC, eu-peregudova commented on src/atoms/filterOption/AppFilterOption.ts
> +        filterOption.classList.toggle('filter-selected');
Hm, don't personally like class use for that, what if we return from the function an object like:
`{element: filterOption, selected: boolean}`

Or you can add `data-` attribute to HTMLElement

2025-01-04 13:18 UTC, Nimiretta commented on src/atoms/filterOption/AppFilterOption.ts
> +        filterOption.classList.toggle('filter-selected');
Fixed

2025-01-04 16:04 UTC, eu-peregudova approved these changes
lgtm 👌

2025-01-05 19:45 UTC, YBiheza approved these changes
looks good to me to)

2025-01-05 19:54 UTC, merged