feat: add counter atom
Nimiretta/js-ts-webdev-tasks pull request #9
Opened 2024-12-29 16:38 UTC by Nimiretta

https://trello.com/c/wJIijMkI

2025-01-02 18:30 UTC, eu-peregudova requested changes

2025-01-02 18:30 UTC, eu-peregudova commented on src/atoms/counter/AppCounter.ts
> +    return counter;
Current value of the counter also needs to be returned for future accessing

2025-01-04 13:59 UTC, Nimiretta commented on src/atoms/counter/AppCounter.ts
> +    return counter;
Fixed

2025-01-04 16:02 UTC, eu-peregudova approved these changes
lgtm ✨

2025-01-05 17:56 UTC, YBiheza commented
ok:)

2025-01-05 18:00 UTC, YBiheza approved these changes
ok

2025-01-05 18:01 UTC, merged